// ============================================================
//  Définition des tableaux du rapport mensuel SIG (DIIS, version AOÛT 2020)
//  Chaque tableau : code, titre, colonnes, lignes + les textes officiels
//  complets (instructions, notes de bas de page) et les questions Oui/Non
//  des sections — repris du formulaire original.
// ============================================================

export const TRANCHES_AGE = ['0-4 ans', '5-9 ans', '10-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et +', 'Total']

// Tranches avec sexe : « 0-4 M », « 0-4 F », …
export function tranchesMF(libelles = TRANCHES_AGE.slice(0, 7)) {
  const cols = []
  for (const l of libelles) {
    cols.push(`${l} M`, `${l} F`)
  }
  return cols
}

export const CONSEILS_UTILISATION = {
  titre: 'CONSEILS D’UTILISATION',
  version: 'Version : AOÛT 2020',
  texte:
    'Le Système d’Information de Gestion (SIG) recueille au travers de ce rapport mensuel un ensemble ' +
    'd’informations sur l’activité, la morbidité, la mortalité et la gestion de votre établissement. Ce rapport ' +
    'complété tous les mois doit être acheminé au Centre de Surveillance Epidémiologique (CSE) de la Direction ' +
    'Départementale de la santé au plus tard le 05 du mois suivant. ' +
    'Afin de réduire les risques d’erreur lors du remplissage de ce rapport, nous vous exhortons à vérifier votre ' +
    'rapport mensuel avant son acheminement au district sanitaire. ' +
    'Ce rapport une fois renseigné au niveau établissement doit faire l’objet d’une vérification par une tierce ' +
    'personne autre que celle qui a élaboré le rapport, puis signé par le responsable de la structure avant d’être ' +
    'déposé au district sanitaire. ' +
    'NB : Au dépôt du rapport au district sanitaire, la personne en charge du rapport doit assister à la vérification ' +
    'effectuée par le CSE afin de valider ensemble le rapport ou relever les anomalies soulignées par le CSE, pour ' +
    'correction. Puis faire emmarger les deux exemplaires du rapport par le CSE une fois celui-ci validé.',
}

export const SECTIONS = [
  {
    code: 'ACTIVITES',
    titre: 'I. ACTIVITES',
    question: 'Des activités de consultations et de soins ont-elles été réalisées ou enregistrées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 1 à 2.',
    siNon: 'Si non, passer à la partie I.2 : « Activités de maternité ».',
    tableaux: ['T1', 'T2'],
  },
  {
    code: 'CPN',
    titre: 'I.2.1 — Activités de consultations prénatales',
    question: 'Des séances de consultations prénatales ont-elles été réalisées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 3 à 5.',
    siNon: 'Si non, passer à la partie I.2.2 : « Accouchements et consultations postnatales ».',
    tableaux: ['T3', 'T4', 'T5'],
  },
  {
    code: 'ACCOUCHEMENTS',
    titre: 'I.2.2 — Accouchements et consultations postnatales',
    question: 'Des accouchements et des consultations postnatales ont-ils été réalisés ou enregistrés dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 6 à 10.',
    siNon: 'Si non, passer à I.2.3 : « Activités de distribution de MILDA et Vitamine A aux enfants ».',
    tableaux: ['T6', 'T7', 'T8', 'T9', 'T10A', 'T10B'],
  },
  {
    code: 'MILDA_VITA',
    titre: 'I.2.3 — Activités de distribution de MILDA et Vitamine A aux enfants',
    question: 'Des Séances de vaccination, de distribution de MILDA, de supplémentation en Vitamine A et de déparasitage des enfants de moins de 5 ans ont-elles été réalisées ou enregistrées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 11 et 12.',
    siNon: 'Si non, passer à la partie I.2.4 : Activités d’évaluation nutritionnelle et prise en charge de la malnutrition.',
    tableaux: ['T11A', 'T11B', 'T12'],
  },
  {
    code: 'NUTRITION',
    titre: 'I.2.4 — Activités d’évaluation nutritionnelle et prise en charge de la malnutrition',
    question: 'Des Séances de dépistage de la malnutrition et de prise en charge de la malnutrition ont-elles été réalisées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 13a et 13b.',
    siNon: 'Si non, passer à la partie I.3 : « Activités de lutte contre le VIH/Sida ».',
    tableaux: ['T13A', 'T13B'],
  },
  {
    code: 'VIH',
    titre: 'I.3 — Activités de lutte contre le VIH/Sida',
    question: 'Des activités de lutte contre le VIH/Sida sont-elles réalisées dans l’établissement ?',
    siOui: 'Si oui, renseigner les tableaux des sections I.3.1 à I.3.4.',
    siNon: 'Si non, passer à « I.4 activités de CCC ».',
    sousSections: [
      {
        titre: 'I.3.1. Conseil dépistage du VIH',
        question: 'Des conseils dépistage hormis PTME ont-ils été réalisés ce mois dans l’établissement ?',
        tableaux: ['T14', 'T15', 'T16'],
      },
      {
        titre: 'I.3.2. Prévention de la Transmission Mère-Enfant du VIH (PTME)',
        question: 'Des activités de PTME ont-elles été réalisées dans l’établissement au cours du mois ?',
        tableaux: ['T17', 'T18', 'T19'],
      },
      {
        titre: 'I.3.3. Activités de suivi des patients séropositifs au VIH',
        question: 'Des activités de PEC/PVVIH ont-elles été réalisées ce mois ?',
        tableaux: ['T20', 'T21A', 'T21B', 'T22', 'T23', 'T24', 'T25', 'T26', 'T27'],
      },
    ],
    tableaux: ['T14', 'T15', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21A', 'T21B', 'T22', 'T23', 'T24', 'T25', 'T26', 'T27'],
  },
  {
    code: 'CCC',
    titre: 'I.4 — Activités de CCC / IEC',
    question: 'Des activités de CCC/IEC ont-elles été menées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner le tableau 28.',
    siNon: 'Si non, passer à la partie I.5 : « Activités de dépistage du cancer du col de l’utérus ».',
    tableaux: ['T28'],
  },
  {
    code: 'CANCER_COL',
    titre: 'I.5 — Dépistage du cancer du col de l’utérus',
    question: 'Des activités de dépistage du cancer du col de l’utérus ont-elles été menées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner le tableau 29.',
    siNon: 'Si non, passer à la partie I.6 : « Activités de planification familiale ».',
    tableaux: ['T29'],
  },
  {
    code: 'PF',
    titre: 'I.6 — Activités de planification familiale',
    question: 'Des activités de planification familiale ont-elles été menées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 30a à 30c.',
    siNon: 'Si non, passer à la partie II : « Morbidité ».',
    tableaux: ['T30A', 'T30B', 'T30C'],
  },
  {
    code: 'MORBIDITE',
    titre: 'II — Morbidité',
    question: 'Des pathologies ont-elles été enregistrées dans l’établissement au cours du mois ?',
    siOui: 'Si oui, renseigner les tableaux 31 à 37.',
    siNon: 'Si non, passer à la partie III : « Mortalité ».',
    tableaux: ['T31', 'T32', 'T33', 'T34', 'T35', 'T36', 'T37'],
  },
  {
    code: 'MORTALITE',
    titre: 'III — Mortalité',
    question: 'Un décès a-t-il été enregistré dans la formation sanitaire au cours du mois ?',
    siOui: 'Si oui, renseigner le tableau 38 et 39.',
    siNon: 'Si non, passer à la quatrième partie IV du rapport « Réalisation des test rapide de dépistage au niveau poste ».',
    tableaux: ['T38', 'T39'],
  },
  {
    code: 'TESTS_RAPIDES',
    titre: 'IV — Tests rapides de dépistage au niveau poste',
    question: 'Des tests rapides de diagnostic du paludisme ou du VIH ont-ils été effectués par prestataires de soins dans la formation sanitaire au cours du mois ?',
    siOui: 'Si oui, renseigner le tableau 40 et 41.',
    siNon: 'Si non, passer à la partie V du rapport « équipements techniques ».',
    tableaux: ['T40', 'T41'],
  },
  {
    code: 'LABORATOIRE',
    titre: 'V.1 — Laboratoire',
    question: 'L’établissement dispose-t-il d’un laboratoire fonctionnel ?',
    siOui: 'Si oui, renseigner les tableaux 42 à 44.',
    siNon: 'Si non, passer à la partie VI.2 : « Activités de Gestion ».',
    tableaux: ['T42', 'T43', 'T44'],
  },
  {
    code: 'FINANCES',
    titre: 'VI.1 — Gestion des finances',
    question: null,
    siOui: null,
    siNon: null,
    tableaux: ['T45', 'T46', 'T47'],
  },
]

const NB = ['Nombre']

export const TABLES = {
  // ── I.1.1 ──
  T1: {
    numero: 1,
    numeroComplet: 'I.1.1. Tableau 1',
    titre: 'Activités de soins curatifs',
    texte: 'Noter le nombre de consultants, consultations, mises en observation, Durée totale des mise en observation en heure, cas référés et cas contre-référés enregistrés dans la formation sanitaire au cours du mois.',
    legende: '*MO : mises en observation. Durée totale des MO* (en heure) = la somme des durées totales des Mises en Observation du mois, exprimée en heure.',
    colonnes: TRANCHES_AGE,
    lignes: [
      'Nombre de consultants',
      'Nombre de consultations',
      'Nombre de MO*',
      'Durée totale des MO* (en heure)',
      'Nombre de cas référés vers une autre structure sanitaire',
      'Nombre de fiches de contre référence reçues',
    ],
  },
  // ── I.1.2 ──
  T2: {
    numero: 2,
    numeroComplet: 'I.1.2. Tableau 2',
    titre: 'Activités de soins infirmiers et petite chirurgie',
    texte: 'Noter le nombre de pansements, d’injections, de perfusions ou d’autres soins réalisés, les circoncisions masculines, les sutures de plaies pendant le mois.',
    legende: '- Consultant = patient qui vient avec un problème de santé pour la première fois (nouveau cas).\n- Consultation = nombre de visites au praticien pour un problème de santé y compris les « contrôles ».',
    colonnes: NB,
    lignes: [
      'Pansements',
      'Injections',
      'Perfusions',
      'Autres soins',
      'Petite chirurgie, circoncision masculine',
      'Petite chirurgie, suture de plaie traumatique',
      'Petite chirurgie, incision d’abcès',
      'Autres petites chirurgies',
    ],
  },
  // ── I.2.1 ──
  T3: {
    numero: 3,
    titre: 'Consultations Prénatales',
    texte: 'Noter le nombre de consultations prénatales de 1er, 2ème, 3ème, 4ème ; 5ème rang et plus.',
    colonnes: NB,
    lignes: [
      'CPN1 au cours du 1er trimestre de la grossesse',
      'CPN1 autre trimestre de la grossesse',
      'Total CPN 1',
      'CPN2',
      'CPN3',
      'CPN4 au 9ème mois de la grossesse',
      'CPN4 autre trimestre de la grossesse',
      'CPN5 et plus',
    ],
  },
  T4: {
    numero: 4,
    titre: 'Dépistage des grossesses à risque',
    texte: 'Noter le nombre de grossesses à risque diagnostiquées en CPN1, le nombre femmes enceintes souffrant de malnutrition ou d’anémie ou dépistées positives à la Syphilis ou à l’AgHBS au cours des consultations prénatale (CPN).',
    colonnes: NB,
    lignes: [
      'Grossesses à risque dépistées en CPN1',
      'Femmes enceintes malnutries dépistées en CPN',
      'Femmes enceintes anémiées dépistées en CPN',
      'Femmes enceintes dépistées positives à la syphilis en CPN',
      'Femmes enceintes dépistées positives à l’AgHBs en CPN',
    ],
  },
  T5: {
    numero: 5,
    titre: 'Prévention au cours de la grossesse',
    texte: 'Noter le nombre de femmes enceintes vues à partir du 4eme mois (16ème semaine) de la grossesse et mises sous Sulfadoxine pyrimétamine, le nombre de femmes enceintes ayant reçu une MILDA, le nombre de femmes enceintes mises sous fer+folate au cours des CPN, le nombre de femmes enceinte déparasitées et le nombre de femmes enceintes qui ont reçu un conseil en PF pour le postpartum.',
    colonnes: NB,
    lignes: [
      'Sulfadoxine pyrimétamine (1ère dose)',
      'Sulfadoxine pyrimétamine (2ème dose)',
      'Sulfadoxine pyrimétamine (3ème dose)',
      'Sulfadoxine pyrimétamine (4ème dose)',
      'Sulfadoxine pyrimétamine (5ème dose et plus)',
      'nombre de femmes enceintes vues en CPN et ayant reçu une MILDA',
      'nombre de femmes enceintes vues en CPN et mise sous Fer + folate Cp',
      'femmes enceintes vues en CPN et déparasitées',
      'Nombre de femmes reçues en CPN qui ont bénéficié d’un counseling PFPPI et de conseils nutritionnels',
    ],
  },
  // ── I.2.2 ──
  T6: {
    numero: 6,
    titre: 'Lieu d’accouchement',
    texte: 'Noter le nombre d’accouchements par lieu et par tranche d’âge pour tous les accouchements enregistrés dans le mois et le nombre de cas référé vers une autre structure sanitaire.',
    colonnes: ['08-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et +', 'Total'],
    lignes: [
      'Accouchement dans l’établissement',
      'Accouchement à domicile',
      'Total',
      'Nombre de cas référés vers une autre structure sanitaire',
    ],
  },
  T7: {
    numero: 7,
    titre: 'Statut Vaccinal au VAT à l’accouchement',
    texte: 'A l’accouchement, noter le nombre de femmes avec un statut vaccinal à jour (correctement vaccinées), non à jour (incomplètement vaccinées), n’ayant bénéficié d’aucune vaccination par le VAT ou dont le statut n’a pas été déterminé le jour de l’accouchement (non vaccinées).',
    colonnes: NB,
    lignes: [
      'Femmes Correctement vaccinées',
      'Femmes Incomplètement vaccinées',
      'Femmes Non vaccinées',
      'Total',
    ],
  },
  T8: {
    numero: 8,
    titre: 'Issue de la grossesse',
    texte: 'Noter le nombre de naissances vivantes, Mort-nés frais, Mort-nés macérés, Enfants nés vivants avec moins de 2500 g, nouveau-nés protégés à la naissance contre le tétanos, avortements spontanés, avortements provoqués.',
    colonnes: NB,
    lignes: [
      'Naissances vivantes',
      'Mort-nés frais',
      'Mort-nés macérés',
      'Enfants nés vivants dont le poids de naissance est inférieur à 2500 g',
      'Prématurés',
      'Nouveau-nés protégés à la naissance contre le tétanos',
      'Accouchements multiples',
      'Avortements spontanés',
      'Avortements provoqués',
    ],
  },
  T9: {
    numero: 9,
    titre: 'Evacuation des mères et des nouveau-nés / Complications obstétricales',
    texte: 'Noter le nombre de mères évacuées avant ou après l’accouchement, le nombre de nouveau-nés évacués, le nombre de complications obstétricales enregistrées, le nombre de complications obstétricales référées au cours du mois.',
    legende: '(*) CO = Complications obstétricales.',
    colonnes: NB,
    lignes: [
      'Evacuation des mères avant l’accouchement',
      'Evacuation des mères après l’accouchement',
      'Evacuation des nouveau-nés',
      'Nombre de femmes ayant présenté une CO*',
      'Nombre de femmes présentant une CO* référées vers une autre structure sanitaire',
    ],
  },
  T10A: {
    numero: 10,
    titre: '10a — Déclaration de naissance en salle d’accouchement',
    texte: 'Noter pour les enfants nés vivants dans le mois, ceux dont une fiche de déclaration de naissance a été renseignée, ceux dont la fiche de déclaration de naissance renseignée comporte les informations nécessaires pour l’attribution d’un numéro d’acte de naissance.',
    legende: '« informations nécessaires » : fiche comportant le nom complet de l’un des parent et le prénom du nouveau-né.',
    colonnes: ['Sexe Masculin', 'Sexe Féminin', 'TOTAL'],
    lignes: [
      'Nombre d’enfants nés vivants au cours du mois dont la fiche de déclaration de naissance a été renseignée',
      '… dont la fiche comporte les « informations nécessaires » pour l’attribution d’un numéro d’acte de naissance',
    ],
  },
  T10B: {
    numero: 10,
    titre: '10b — Consultations postnatales',
    texte: 'Noter le nombre de femmes suivi/reçues en consultations postnatales (immédiat de 6h à 72h après l’accouchement, entre le 6eme et le 10ème jours après l’accouchement, consultations postnatales autres périodes (entre 72h et 06 jours, puis entre 10 jours et la 6ème semaines), les consultations postnatales entre 6 semaines et 08 semaines après l’accouchement.',
    colonnes: NB,
    lignes: [
      'Consultation postnatale immédiate (dans les 6 à 72 heures suivant l’accouchement)',
      'Consultation postnatale entre 6e et 10e jours après l’accouchement',
      'Consultation postnatale autres périodes (>72h et <6 jours ; >10 jrs et < 6ème semaine)',
      'Consultation postnatale (6ème semaine à 8ème semaine)',
    ],
  },
  // ── I.2.3 ──
  T11A: {
    numero: 11,
    titre: '11a — distribution de MILDA aux enfants',
    texte: 'Noter le nombre d’enfants vus en séance PEV de routine, ayant reçu une MILDA en PEV, « éligibles » à la MILDA vus en consultations curatives et ceux ayant reçus les MILDA en consultations curatives.',
    colonnes: ['0-5 mois', '6-11 mois', '12-59 mois', 'Total'],
    lignes: [
      'Nombre d’enfants vus en séance de vaccination PEV de routine',
      'Nombre d’enfants ayant reçu une MILDA au cours du PEV',
      'Nombre d’enfants « éligible » à la MILDA vus en consultations et soins curatifs',
      'Nombre d’enfants ayant reçu une MILDA au cours des consultations et soins curatifs',
    ],
  },
  T11B: {
    numero: 11,
    titre: '11b — Déclaration de naissance en séance de vaccination',
    texte: 'Noter pour les enfants vus en séance de vaccination PEV, ceux qui ne possèdent pas d’acte de naissance, ceux dont une fiche de déclaration de naissance a été renseignée, ceux dont la fiche de déclaration de naissance renseignée comporte les informations nécessaires pour l’attribution d’un numéro d’acte de naissance.',
    legende: '« informations nécessaires » : fiche comportant le nom complet de l’un des parent et le prénom de l’enfant.',
    colonnes: ['Sexe Masculin', 'Sexe Féminin', 'TOTAL'],
    lignes: [
      'Nombre d’enfants reçus à la vaccination ne disposant pas d’acte de naissance',
      '… dont la fiche de déclaration de naissance a été renseignée',
      '… dont la fiche comporte les « informations nécessaires » pour l’attribution d’un numéro d’acte de naissance',
    ],
  },
  T12: {
    numero: 12,
    titre: 'Supplémentation en vitamine A et déparasitage des enfants de moins de 5 ans',
    texte: 'Noter le nombre d’enfant de moins de 5 ans supplémentés en Vitamine A première dose, deuxième dose et le nombre d’enfants déparasités.',
    colonnes: ['06 à 11 mois', '12 A 59 mois', 'TOTAL'],
    lignes: [
      'Nombre d’enfants supplémentés Vitamine A, 1ière dose',
      'Nombre d’enfants supplémentés Vitamine A, 2ième dose',
      'Nombre d’enfants déparasités',
    ],
  },
  // ── I.2.4 ──
  T13A: {
    numero: 13,
    titre: '13a — Etat nutritionnel',
    texte: 'Noter le nombre de personnes ayant bénéficiées d’une évaluation nutritionnelle au cours du mois, celles dépistées malnutris, en surpoids, obèses et les retards de croissance.',
    legende: 'Les PVVIH sont compris dans ce tableau.',
    colonnes: [
      ...tranchesMF(['0-5 mois', '6-11 mois', '12-23 mois', '24-59 mois', '5-9 ans', '10-14 ans', '15-19 ans', '20-24 ans', '25 ans et +']),
      'F.E', 'F.A', 'Total', 'Total référés',
    ],
    lignes: [
      'Nombre de personnes ayant bénéficié d’une évaluation nutritionnelle (prise poids et taille)',
      'Malnutris aigüe sévères sans complication',
      'Malnutris aigüe sévères avec complication',
      'Malnutris aigüe modérés',
      'Surpoids',
      'Obésité',
      'Retard de croissance',
    ],
  },
  T13B: {
    numero: 13,
    titre: '13b — Prise en charge de la Malnutrition aigüe',
    texte: 'Noter le Nombre de personnes malnutries prises en charge, le nombre de malnutris déclarés guéris, le nombre ayant abandonné le traitement et les décès imputables à la malnutrition.',
    legende: 'Décès* : le chiffre doit être reporté dans le tableau 38 « mortalité ».',
    colonnes: [
      ...tranchesMF(['0-5 mois', '6-11 mois', '12-23 mois', '24-59 mois', '5-9 ans', '10-14 ans', '15-19 ans', '20-24 ans', '25 ans et +']),
      'F.E', 'F.A', 'Total',
    ],
    lignes: [
      'Nombre de malnutris pris en charge',
      'Nombre de malnutris aigue sévère sans complication déclarés guéris',
      'Nombre de malnutris aigue modérés déclarés guéris',
      'Abandon traitement',
      'Décès*',
    ],
  },
  // ── I.3.1 ──
  T14: {
    numero: 14,
    titre: 'Conseils et dépistage (hormis le conseil dépistage réalisé en PTME)',
    texte: 'Noter le Nombre de personnes conseillées, dépistées pour le VIH, ayant reçu leur résultat (hormis données de PTME), dépistées positives au VIH, le nombre de personnes dépistées à la suite d’un autotest réactif, le nombre de personnes ayant bénéficié d’un retesting.',
    legende: '*Sous ensemble du nombre de clients dépistés/dépistés positif, le retesting est compris dans le nombre de clients conseillés et dépistés pour le VIH ayant reçu le résultat du test.',
    colonnes: [...tranchesMF(), 'TOTAL'],
    lignes: [
      'Nombre de clients conseillés',
      'Nombre de clients conseillés et dépistés pour le VIH ayant reçu le résultat du test',
      'Nombre de clients dépistés positif',
      'Nombre de personnes dépistées après la réalisation d’un auto-test VIH réactif*',
      'Nombre de personnes confirmées positives au VIH après la réalisation d’un auto-test VIH réactif*',
      'Nombre de personnes dépistées par retesting',
    ],
  },
  T15: {
    numero: 15,
    titre: 'Conseils et dépistage du VIH chez la population à haut risque d’exposition',
    texte: 'Noter le nombre de TS, UD, HSH conseillés, dépistés et dépistés positif au VIH au cours du mois.',
    legende: '*TS : Travailleuse de sexe · *UD : Utilisateur de Drogue · *HSH : Homme Sexe Homme.',
    colonnes: ['TS*', 'UD*', 'HSH*', 'Total'],
    lignes: [
      'Nombre de clients conseillés pour le VIH',
      'Nombre de clients conseillés et dépistés pour le VIH ayant retiré le résultat du test',
      'Nombre de clients dépistés positif au VIH',
    ],
  },
  T16: {
    numero: 16,
    titre: 'Dépistage du VIH chez les patients présentant une IST',
    texte: 'Noter le Nombre de personnes atteintes d’une IST et dépisté au VIH, le nombre de personne atteinte d’une IST et dépistées positives au VIH au cours du mois (y compris les données en CPN, maternité et postnatale).',
    colonnes: [...tranchesMF(['10-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et +']), 'Total'],
    lignes: [
      'Nombre de personnes atteintes d’une IST dépistées au VIH',
      'Nombre de personnes atteintes d’une IST dépistées positives au VIH',
    ],
  },
  // ── I.3.2 ──
  T17: {
    numero: 17,
    titre: 'Conseil et dépistage en CPN, en maternité et en postnatal',
    texte: 'Noter le nombre de femmes enceintes reçues en CPN 1 et se connaissant déjà séropositive au VIH, Nombre de femmes enceintes déjà sous traitement ARV et reçues en CPN1, nombre de femmes enceintes conseillées et dépistées en CPN1 qui ont reçu leur résultat du test VIH, nombre de femme enceinte/allaitantes conseillées et testée pour le VIH qui ont reçu leur résultats en CPN, en Maternité et en Postnatal, Nombre de femmes enceintes séronégatives au VIH qui ont bénéficié d’un retesting, nombre de femmes enceintes/allaitantes dépistées positives au VIH, Nombre de femme enceintes/allaitantes dépistées positives au VIH nouvellement mise sous ARV, Nombre de femme enceinte séropositives au VIH sous ARV qui ont une charge virale inférieure ou égale à 1000 copies/ml au dernier trimestre de la grossesse.',
    colonnes: ['CPN', 'MATERNITE', 'POST NATAL', 'TOTAL'],
    lignes: [
      'Nombre de femmes enceintes reçues en CPN 1 et se connaissant déjà séropositives au VIH',
      'Nombre de femmes enceintes déjà sous traitement ARV et reçues en CPN 1',
      'Nombre de femmes enceintes conseillées et testées pour le VIH, qui ont reçu leur résultat du test VIH en CPN 1',
      'Nombre de femmes enceintes/allaitantes conseillées et testées pour le VIH, qui ont reçu leur résultat du test VIH',
      'Nombre de femmes enceintes séronégatives au VIH ayant bénéficié d’un « retesting »',
      'Nombre de femmes enceintes/allaitantes dépistées positives au VIH',
      'Nombre de femmes enceintes/allaitantes séropositives au VIH nouvellement mise sous ARV',
      'Nombre de femmes enceintes séropositives au VIH sous traitement ARV chez qui le résultat de la charge virale est ≤ 1000 copies/ml dans le dernier trimestre de la grossesse',
    ],
  },
  T18: {
    numero: 18,
    titre: 'Suivi des mères et des enfants nés de mères séropositives au VIH',
    texte: 'Noter le nombre d’enfants nés vivants de mères séropositives au VIH (dans un établissement de santé ou à domicile) enregistré dans l’établissement, y compris ceux vus après 72 heures), le nombre d’enfants qui ont reçu la prophylaxie ARV dans les 72h après leur naissance, nombre d’enfant initiant le Cotrimoxazole avant l’âge de 02 mois.',
    colonnes: ['Effectifs'],
    lignes: [
      'Nombre de femmes enceintes séropositives au VIH dont l’accouchement a été enregistré au cours du mois (accouchement dans l’établissement/accouchement à domicile)',
      'Nombre d’enfants nés vivants de mères séropositives au VIH',
      'Nombre d’enfants nés de mères séropositives au VIH ayant reçu des ARV dans les 72 h après la naissance',
      'Nombre d’enfants nés de mères séropositives au VIH initiant la prophylaxie au Cotrimoxazole avant 02 mois',
    ],
  },
  T19: {
    numero: 19,
    titre: 'Dépistage du VIH chez les enfants nés de mères séropositive au VIH',
    texte: 'Noter le nombre d’enfants nés de mères séropositives au VIH dépisté (DBS ou sérologie) précocement ou tardivement, dépistés positifs, dépistés positifs de mis sous ARV, dépistés VIH positif et référés vers un autre établissement offrant la Prise en charge VIH.',
    legende: '*Les références internes (entre service d’un même établissement de santé) ne sont pas concernées.',
    colonnes: ['Effectifs'],
    lignes: [
      'Nombre d’enfants nés de mères séropositives au VIH dépistés précocement (avant 2 mois)',
      'Nombre d’enfants nés de mères séropositives au VIH dépistés précocement (2 à 09 mois)',
      'Nombre d’enfants nés de mères séropositives au VIH dépistés tardivement (10 à 18 mois)',
      'Nombre d’enfants nés de mères séropositives au VIH dépistés VIH positif',
      'Nombre d’enfants nés de mères séropositives au VIH dépistés VIH positif, nouvellement mis sous traitement ARV',
      'Nombre d’enfants nés de mères séropositives au VIH dépistés VIH positif et référés vers un autre établissement offrant la PEC*',
    ],
  },
  // ── I.3.3 ──
  T20: {
    numero: 20,
    titre: 'Soins des PVVIH — nouveaux patients enregistrés et patients suivis',
    texte: '- Noter le nombre de patients dépistés positifs au VIH dans la communauté (par les communautaires) et référés dans l’établissement puis enrôlés dans les soins VIH au cours du mois.\n- Nombre de patients dépistés positifs au VIH dans un autre établissement de santé n’ayant pas encore été enrôlés dans les soins VIH, référés dans la structure et enrôles dans les soins au cours du mois.\n- Nombre de patients dépisté positifs au VIH dans l’établissement et enrôlés dans les soins VIH au cours du mois.\n- Nombre total de patient VIH positifs ayant reçus les soins VIH au cours du mois (anciens + nouveaux), y compris ceux qui sont sous traitement ARV qui ne sont pas passés sur le site dans le mois mais qui ont une dotation d’ARV couvrant le mois.',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprises dans le total des femmes.',
    colonnes: [...tranchesMF(), 'Total', 'Femmes enceintes*', 'Femmes allaitantes*'],
    lignes: [
      'Patients dépistés positifs au VIH dans la communauté, référés et nouvellement enrôlés dans les soins VIH dans l’établissement au cours du mois',
      'Patients dépistés positifs au VIH dans un autre établissement, non encore enrôlés dans les soins, référés et nouvellement enrôlés dans les soins VIH au cours du mois',
      'Patients dépistés positifs au VIH dans l’établissement et enrôlés dans les soins VIH au cours du mois',
      'Patients VIH positif qui ont reçu les soins VIH (y compris ARV) dans l’établissement au cours du mois',
    ],
  },
  T21A: {
    numero: 21,
    titre: '21a — Suivi biologique des PVVIH',
    texte: 'Noter le nombre de patients VIH positifs qui ont bénéficié d’un bilan initial (biologique) dont les résultats ont été reçus au cours du mois, Nombre de PVVIH qui a bénéficié d’un bilan biologique de suivi dont les résultats ont été reçus au cours du mois, le nombre de PVVIH qui ont bénéficié d’une charge virale dont les résultats ont été reçus au cours du mois (la charge virale est comprise dans bilan biologique), le nombre de PVVIH dont le résultat de la charge virale est inférieur ou égal à 1000 copie/ml.',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprise dans le total des femmes.\n**La charge virale fait partie du bilan biologique.',
    colonnes: [...tranchesMF(), 'Total', 'Femmes enceintes*', 'Femmes allaitantes*'],
    lignes: [
      'Patients VIH positif ayant bénéficié d’un bilan initial (biologique) au cours du mois',
      'Patients VIH positif ayant bénéficié d’un bilan biologique de suivi au cours du mois',
      'Patients VIH positif dont le résultat de la charge virale** a été reçu au cours du mois',
      'Patients VIH positif sous traitement ARV dont le résultat de la charge virale est ≤ 1000 copies/ml au cours du mois',
    ],
  },
  T21B: {
    numero: 21,
    titre: '21b — Suivi des patients stables et patients dans les soins différenciés',
    colonnes: ['Enfant < 15 ans', 'Adulte ≥ 15 ans'],
    lignes: [
      'Nombre de patient VIH positif sous ARV classés stables',
      'Nombre de patient VIH positif sous ARV enrôlés dans les soins différenciés',
    ],
  },
  T22: {
    numero: 22,
    titre: 'Evaluation nutritionnelle des PVVIH',
    texte: 'Noter le nombre de Patients VIH positifs qui ont bénéficié d’une évaluation nutritionnelle au cours du mois, noter le nombre de Patients VIH positifs dépistés malnutris au cours du mois, noter le nombre de Patients VIH positifs dépistés malnutris au cours du mois et qui ont bénéficié d’un traitement nutritionnel.',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprise dans le total des femmes.',
    colonnes: [...tranchesMF(), 'Total', 'Femmes enceintes*', 'Femmes allaitantes*'],
    lignes: [
      'Nombre de patients VIH positif ayant bénéficié d’une évaluation nutritionnelle au cours du mois',
      'Nombre de patients VIH positif dépistés malnutris au cours du mois',
      'Nombre de Patients VIH positif dépistés malnutris, qui ont bénéficié d’un traitement nutritionnel au cours du mois',
    ],
  },
  T23: {
    numero: 23,
    titre: 'Patient sous Traitement ARV',
    texte: 'Noter le nombre de Patients dépistés positifs au VIH au cours du mois dans l’établissement et mis sous ARV dans l’établissement au cours du mois. Nombre de patients dépistés positifs au VIH les mois antérieurs et qui n’avaient pas encore initié le traitement ARV, puis mis sous ARV dans l’établissement au cours du mois. Nombre de patients dépistés positifs au VIH dans un autre établissement de santé ou dans la communauté, n’ayant pas encore initié le traitement ARV et mis sous ARV dans l’établissement au cours du mois. Noter le nombre de patients dépistés positifs au VIH qui commencent nouvellement le traitement ARV (la première fois de leur vie, naïf) au cours du mois dans l’établissement, le nombre de patients sous ARV (file active), passés récupérer les ARV dans le mois ou ayant une dotation d’ARV qui couvre le mois (retirer les décédés, perdus de vue, arrêt traitement).',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprise dans le total des femmes.',
    colonnes: [...tranchesMF(), 'Total', 'Femmes enceintes*', 'Femmes allaitantes*'],
    lignes: [
      'Patients dépistés positif au VIH dans l’établissement au cours du mois et mis sous ARV dans l’établissement au cours du mois',
      'Patients dépistés positif au VIH les mois antérieurs dans l’établissement, n’ayant pas encore initié le traitement ARV et mis sous ARV dans l’établissement au cours du mois',
      'Patients dépistés positif au VIH dans un autre établissement ou dans la communauté, n’ayant pas commencé les ARV et mis sous ARV dans l’établissement au cours du mois',
      'Patients VIH positif ayant nouvellement commencé (initié) le traitement ARV dans l’établissement au cours du mois',
      'Patients VIH positif sous ARV (file active)',
    ],
  },
  T24: {
    numero: 24,
    titre: 'Soins préventifs / Coïnfection TB/VIH',
    texte: 'Noter le nombre de Patients VIH positif chez qui une recherche active de la TB a été effectuée lors de leur dernière visite ; Le nombre de patients VIH positif présumé tuberculeux chez qui la tuberculose a été diagnostiquée au cours du mois ; Le Nombre de patients VIH positif qui ont débuté le traitement de la tuberculose dans l’établissement au cours du mois ; Le nombre de patients VIH positif qui reçoivent le traitement ARV et le traitement de la tuberculose à la fois au cours du mois ; Le nombre de patients VIH positifs qui ont bénéficié de la thérapie préventive de la tuberculose (TPT) au cours du mois.',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprise dans le total des femmes.',
    colonnes: [...tranchesMF(), 'Total', 'Femmes enceintes*', 'Femmes allaitantes*'],
    lignes: [
      'Nombre de patients VIH positif ayant bénéficié d’une recherche active de la tuberculose à la dernière visite',
      'Nombre de Patients VIH positif présumés tuberculeux chez qui la tuberculose a été diagnostiquée',
      'Nombre de patients VIH positif ayant débuté le traitement de la tuberculose dans l’établissement',
      'Nombre de patients VIH positif sous traitement ARV et qui reçoivent également le traitement de la tuberculose dans l’établissement',
      'Nombre de patients VIH positif bénéficiant de la thérapie préventive de la tuberculose (TPT)',
    ],
  },
  T25: {
    numero: 25,
    titre: 'Accident d’exposition au sang et autres liquides biologiques / Prophylaxie pré exposition (PrEP)',
    texte: 'Noter le nombre de nouveaux cas d’exposition au sang et autre liquides biologiques (professionnel, violence sexuelle, rupture de préservatif ou autre type d’AES). Le nombre de nouveaux cas de prophylaxie Préexposition (PrEP) enregistrés au cours du mois.',
    colonnes: ['Masculin', 'Féminin', 'Total'],
    lignes: [
      'Nombre de nouveau cas d’AES de type Professionnel (agent de santé)',
      'Nombre de nouveau cas d’AES de type Violence sexuelle',
      'Nombre de nouveau cas d’AES de type Rupture de préservatif',
      'Nombre de nouveau cas d’Autres types de AES',
      'Nombre de nouveau cas de PrEP',
    ],
  },
  T26: {
    numero: 26,
    titre: 'Patients qui ne sont pas venus chercher leurs ARV au cours du mois',
    texte: 'Noter le nombre de patients sous ARV attendus dans le mois pour s’approvisionner et que ne sont pas venus à leur rendez-vous ; Nombre de patients sous ARV qui sont déclarés perdus de vue au cours du mois. Nombre de patients sous ARV qui sont décédés au cours du mois ou dont le décès a été rapporté au cours du mois.',
    legende: 'Femmes enceintes* et Femmes allaitantes* sont comprise dans le total des femmes.\nDécédé : le chiffre doit être reporté dans le tableau 38 « mortalité ».',
    colonnes: ['1. Patient sous ARV attendu qui ne sont pas venus à leur RDV ce mois', '2. Perdu de vue', '3. Décédé'],
    lignes: [
      ...TRANCHES_AGE.slice(0, 7).map((l) => `${l} M`),
      ...TRANCHES_AGE.slice(0, 7).map((l) => `${l} F`),
      'Total',
      'Femmes enceintes*',
      'Femmes allaitantes*',
    ],
  },
  T27: {
    numero: 27,
    titre: 'Suivi de cohorte — Patient sous traitement ARV',
    colonnes: ['Enfant', 'Adulte'],
    lignes: [
      'Nombre total de patients de la cohorte en vie et sous traitement ARV 12 mois après le début du traitement (V)',
      'Nombre total de patients de la cohorte sous traitement de 2ème ligne 12 mois après le début du traitement (J)',
      'Nombre total de patients de la cohorte à 12 mois de suivi (Z)',
      'Nombre de patients de la cohorte sous ARV chez qui la charge virale a été demandée 12 mois après la mise sous ARV',
      'Nombre de patients de la cohorte sous ARV avec un résultat de la charge virale ‹ 1000 copies/ml à 12 mois après la mise sous TARV (suppression de la charge virale)',
    ],
  },
  // ── I.4 ──
  T28: {
    numero: 28,
    titre: 'CCC',
    texte: 'Noter pour chaque thème présenté, le nombre de séances consacrées à ce thème et le nombre de participants.',
    legende: '* PCIME-C : Prise en charge intégrée des maladies de l’enfant au niveau communautaire.',
    colonnes: ['Nombre de séances', 'Nombre de participants'],
    lignes: [
      'Planification familiale',
      'Actions essentielles en nutrition plus (AEN+)',
      'SIDA/ IST',
      'Bonnes pratiques d’Hygiène',
      'Hygiène buccodentaire',
      'Paludisme',
      'Cancers (col de l’utérus et sein)',
      'Promotion des pratiques familiales essentielles (PCIME-C)*',
    ],
  },
  // ── I.5 ──
  T29: {
    numero: 29,
    titre: 'Dépistage du cancer du col de l’utérus',
    texte: 'Noter le nombre femmes dépistées pour le cancer du col de l’utérus par l’IVA au cours du mois, femmes séropositives au VIH dépistées pour le cancer du col de l’utérus par l’IVA, femmes dépistées présentant des lésions précancéreuses du col de l’utérus, femmes séropositives au VIH présentant des lésions précancéreuses du col de l’utérus, femmes dépistées présentant des lésions précancéreuses du col de l’utérus référées vers une structure, le nombre d’IVA positive ayant reçues un traitement de cryothérapie.',
    legende: '*IVA : Inspection Visuelle à l’Acide Acétique.\nNB : le nombre de femmes séropositives au VIH est compris dans le total des femmes.',
    colonnes: ['10-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et plus', 'Total'],
    lignes: [
      'Nombre de femmes dépistées pour le cancer du col de l’utérus par l’IVA*',
      'Nombre de femmes séropositives au VIH dépistées pour le cancer du col de l’utérus par l’IVA',
      'Nombre de femmes dépistées présentant des lésions précancéreuses du col de l’utérus',
      'Nombre de femmes séropositives au VIH présentant des lésions précancéreuses du col de l’utérus',
      'Nombre de femmes dépistées présentant des lésions précancéreuses du col de l’utérus référées vers une structure',
      'Nombre de femmes IVA positive ayant reçues un traitement de cryothérapie',
    ],
  },
  // ── I.6 ──
  T30A: {
    numero: 30,
    titre: '30a — Contraception moderne',
    colonnes: [
      'Nouvelles < 15 ans',
      'Nouvelles 15-19 ans',
      'Nouvelles 20-24 ans',
      'Nouvelles 25 ans et +',
      'Nouvelles Total',
      'Anciennes utilisatrices',
      'Nombre total d’utilisatrices',
      'Protégées',
      'Perdues de vues',
      'Abandons',
      'Arrêts/Retraits',
    ],
    lignes: [
      'Pilule (COC)',
      'Pilule (COP)',
      'Injectable IM 3 mois',
      'Injectable IM 2 mois',
      'Injectable sous Cutané 3 mois',
      'Auto-injection 3 mois',
      'DIU',
      'DIU-PP',
      'Implant 5 ans',
      'Implant 3 ans',
      'Condom masculin',
      'Condom Féminin',
      'Spermicide',
      'Contraception d’urgence',
    ],
  },
  T30B: {
    numero: 30,
    titre: '30b — Autres indicateurs d’activités en PF',
    colonnes: NB,
    lignes: [
      'Nombre de femmes ayant reçu un counseling en Planification Familiale dans le post partum',
      'Nombre de femmes ayant reçu un produit contraceptif dans le post partum immédiat',
      'Nombre de femmes ayant reçu un produit contraceptif dans le post abortum',
      'Nombre total de consultations en Planification Familiale',
      'Nombre total de femmes ayant changé de méthode',
      'Nombre de femmes formées à l’auto-injection',
      'Nombre de femmes reçues dans les services de PF qui présentent une IST',
      'Nombre de femmes séropositives au VIH sous contraception moderne (toutes méthodes confondues)',
      'Nombre de femmes avec nourrisson de 0-6 mois reçues en PF, qui ont reçu des conseils nutritionnels dont l’enfant est à jour de ses vaccins',
      'Nombre de femmes avec nourrisson de 6 mois reçues en PF, ayant reçu des conseils sur l’alimentation complémentaire et dont l’enfant a reçu la vitamine A',
    ],
  },
  T30C: {
    numero: 30,
    titre: '30c — Gestion de stock de contraceptifs',
    texte: 'Noter pour les contraceptifs cités, les quantités reçues, distribuée et restante pendant le mois.',
    colonnes: [
      'Stock Initial',
      'Quantité Reçue',
      'Quantité distribuée aux clients',
      'Autres quantités sorties (Perte/Ajustement)',
      'Quantité en stock (SDU)',
      'Nombre de Jours de rupture',
    ],
    lignes: [
      'Pilule (COC)',
      'Pilule (COP)',
      'Injectable IM 3 mois',
      'Injectable IM 2 mois',
      'Injectable sous Cutané 3 mois',
      'DIU',
      'DIU-PP',
      'Implant 5 ans',
      'Implant 3 ans',
      'Condom masculin',
      'Condom Féminin',
      'Spermicide',
      'Contraception d’urgence',
    ],
  },
  // ── II. Morbidité ──
  T31: {
    numero: 31,
    titre: 'Maladies infectieuses',
    texte: 'Noter le nombre de cas de maladie diagnostiqués lors des consultations curatives, le nombre de cas référés.',
    legende: 'FE = femme enceinte · CS = cas suspect · IRA : Infection Respiratoire Aiguë · CTA = Combinaison Thérapeutique à base d’Artémisinine · SRO = Sel de Réhydratation Orale.\n*FE = femmes enceintes est compris dans le total.',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'Total', 'Cas référés'],
    lignes: [
      'Cas suspects de Paludisme simple (y compris femme enceinte)',
      'Cas suspects de Paludisme simple femme enceinte',
      'Cas de Paludisme simple (y compris femme enceinte)',
      'Cas de Paludisme simple chez la femme enceinte',
      'Cas suspects de Paludisme graves (y compris femme enceinte)',
      'Cas suspects de Paludisme graves chez la femme enceinte',
      'Diarrhée aiguë sans déshydratation',
      'Diarrhée aiguë avec signes évidents de déshydratation',
      'Diarrhée aiguë avec déshydratation sévère',
      'Diarrhée aiguë sanglante',
      'Pneumonie simple (IRA basse)',
      'Pneumonie grave (IRA basse)',
      'Broncho-pneumonie (IRA basse)',
      'Otite moyenne aigue (IRA haute)',
      'Rhinopharyngite (IRA haute)',
      'Angine (IRA haute)',
      'Sinusite (IRA haute)',
      'Laryngite (IRA haute)',
      'Pian',
      'Cas suspects de bilharziose urinaire',
      'Cas suspect de trichiasis trachomateux',
      'Cas suspects d’hydrocèle',
      'Cas suspects de lymphœdème',
      'Tétanos',
      'Coqueluche',
      'Fièvre Typhoïde',
      'Fièvre Jaune',
      'Choléra',
      'Méningite',
      'Tuberculose (CS)',
      'Ulcère de buruli (CS)',
      'Varicelle',
      'Dermatose',
      'Zona',
      'Hépatite virale B',
      'Hépatite virale C',
      'Autres Maladies infectieuses',
      'Cas de Paludisme simple avec prescription de CTA (y compris femme enceinte)',
      'Cas de Paludisme simple chez la femme enceinte avec prescription de CTA',
      'Cas de Paludisme simple chez la femme enceinte avec prescription de quinine comprimé',
      'Cas suspect de paludisme avec prescription de CTA (présumé), y compris femme enceinte',
      'Cas suspect de paludisme chez la femme enceinte avec prescription de CTA (présumé)',
      'Nombre d’enfants de moins de 5 ans atteints de la pneumonie et ayant reçu une prescription d’antibiotique',
      'Nombre d’enfants de moins de 5 ans atteints de la diarrhée et ayant reçu une prescription de SRO + Zinc',
    ],
  },
  T32: {
    numero: 32,
    titre: 'Infections sexuellement transmissibles',
    texte: 'Noter le nombre de cas diagnostiqués pour les syndromes de IST cités et le nombre de cas référés vers une autre structure.',
    colonnes: [...tranchesMF(['0-28 jours', '10-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et plus']), 'Total', 'Cas référés vers une autre structure'],
    lignes: [
      'Conjonctivite du nouveau-né',
      'Ecoulement urétral masculin et/ou douleur et/ou prurit et/ou gêne intra urétrale',
      'Ecoulement vaginal et/ou brûlure ou prurit et/ou mal odeur vaginale',
      'Ulcération génitale et/ou bubon',
      'Douleurs testiculaires',
      'Douleurs abdominales basses (pelviennes) chez la femme',
      'Condylomes (végétations vénériennes ou crêtes de coq)',
    ],
  },
  T33: {
    numero: 33,
    titre: 'Violences basées sur le genre',
    texte: 'Noter le nombre de cas de violences sexuelles dont les victimes ont été reçues en consultation dans les 72 heures après l’acte, le nombre de cas pris en charge dans l’établissement, le nombre de cas référés.',
    colonnes: tranchesMF(),
    lignes: [
      'Nombre de survivants aux violences sexuelles ayant consulté dans les 72 heures',
      'Nombre de survivants aux violences sexuelles pris en charge dans l’établissement',
      'Nombre de survivants aux violences sexuelles référés vers une autre structure',
    ],
  },
  T34: {
    numero: 34,
    titre: 'Affections bucco-dentaires',
    texte: 'Noter le nombre de maladies buccodentaires diagnostiquées lors des consultations du mois.',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'TOTAL', 'Cas référés'],
    lignes: [
      'Trouble de l’ATM',
      'Trouble du frein lingual',
      'Carie',
      'Malocclusion',
      'Gingivite',
      'Bruxisme/ usure dentaire',
      'Poches parodontales',
      'Parodontolyses',
      'Infection apicale',
      'Cellulite',
      'Plaque dentaire',
      'Tartre',
      'Halitose',
      'Noma',
      'Burkit',
      'Traumatisme bucco-dentaire',
      'Candidoses buccales',
      'Autres affections dentaires',
    ],
  },
  T35: {
    numero: 35,
    titre: 'Traitements réalisées au cabinet dentaire',
    texte: 'Noter le nombre de traitements réalisés au cours du mois selon le type.',
    legende: 'OP : obturation préventive · Détart : Détartrage · OC : obturation coronaire · TR : traitement radiculaire · TP : traitement parodontal · TC : traitement chirurgical · ODF : orthopédie dento-faciale.',
    colonnes: ['OP', 'Détart', 'OC', 'TR', 'TP', 'Extraction', 'TC', 'Prothèse', 'ODF', 'Fluor', 'Autres'],
    lignes: ['Nombre de traitements réalisés'],
  },
  T36: {
    numero: 36,
    titre: 'Affections oculaires',
    texte: 'Noter le nombre d’affections oculaires diagnostiquées au cours du mois, selon le type.',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'Total', 'Cas référés'],
    lignes: [
      'Cataracte',
      'Cécité',
      'Blépharite',
      'Chalazion/Orgelet',
      'Conjonctivite Allergique',
      'Conjonctivite infectieuse',
      'Trachome',
      'Autres affections oculaires',
    ],
  },
  T37: {
    numero: 37,
    titre: 'Maladies non transmissibles et facteurs de risque cardiovasculaire',
    texte: 'Noter le nombre de cas de maladies non transmissibles et les facteurs de risque cardiovasculaire, diagnostiqués lors des consultations curatives et les cas référés vers une autre structure.',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'Total', 'Cas référés'],
    lignes: [
      'HTA sans antécédent de HTA connu chez les adultes, y compris femme enceinte',
      'HTA sans antécédent de HTA connu chez les femmes enceintes (adultes)',
      'HTA avec antécédent de HTA connu chez les adultes, y compris femme enceinte',
      'HTA avec antécédent de HTA connu chez les femmes enceintes (adultes)',
      'Hyperglycémie sans antécédents de diabète connu',
      'Diabète Gestationnel',
      'Asthme',
      'Drépanocytose',
      'Insuffisance rénale aigüe',
      'Accidenté de la voie publique',
      'Troubles psychiatriques',
      'Retard psychomoteurs',
      'Anémie modérée',
      'Anémie grave',
      'GEU',
      'Fibrome utérin',
      'Appendicite',
      'Occlusion intestinale',
      'Hernie',
      'Péritonite',
      'Goitre',
      'Brûlure',
      'Accident vasculaire cérébral (AVC)',
      'Morsure de serpent',
      'Tentative de suicide',
      'Autres traumatismes',
      'Maladie indéterminée',
      'Autres Maladies non infectieuses',
    ],
  },
  // ── III. Mortalité ──
  T38: {
    numero: 38,
    titre: 'Notification des décès',
    texte: 'Noter le nombre de décès enregistré dans l’établissement selon la cause probable (cause initiale inscrite dans le registre de décès).',
    colonnes: [...tranchesMF(), 'Total M', 'Total F', 'Total global'],
    cim: [
      'B50-B54', 'B20-B24', 'B05', 'A33-A35', 'A01', 'A15-A19', 'J00-J22', 'E40-E46',
      'D50-D64', 'A09', 'A95', 'A00', 'E10-E14', 'I60-I64', 'G00-G03', 'A90-A99',
      'A09', 'B99', 'V01-V99', 'S00-S09', 'T00-T98', 'K35-K37', 'K56', 'K40-K46',
      'K65', 'N44', '—', '—', 'O00', 'O85-O92', 'D25', 'N80-N98', 'X20', 'R98',
      'X60-X84', 'R99', '—',
    ],
    lignes: [
      'Paludisme',
      'VIH/Sida',
      'Rougeole',
      'Tétanos',
      'Fièvre Typhoïde',
      'Tuberculose',
      'IRA',
      'Malnutrition',
      'Anémie',
      'Diarrhées non Sanglante',
      'Fièvre Jaune',
      'Choléra',
      'Diabète',
      'Accident vasculaire cérébral (AVC)',
      'Méningite',
      'Fièvre hémorragique',
      'Diarrhées sanglantes',
      'Autres maladies infectieuses',
      'Accidenté de la voie publique',
      'Traumatisme crânien',
      'Autres traumatisme',
      'Appendicite',
      'Occlusion intestinale',
      'Hernie',
      'Péritonite',
      'Torsion testiculaire',
      'Autres maladies chirurgie',
      'Autres maladies non infectieuses',
      'GEU',
      'Complications obstétricales',
      'Fibrome utérin',
      'Autres maladies en gynéco',
      'Morsure de serpent',
      'Arrivé décédé',
      'Suicide',
      'Causes indéterminées',
      'Total Général',
    ],
  },
  T39: {
    numero: 39,
    titre: 'Décès maternel et Néonatal',
    texte: 'Noter le nombre de décès maternel et néonatal enregistré dans l’établissement au cours du mois.',
    legende: 'NB : ce tableau est un sous ensemble du tableau 38.',
    colonnes: ['08-14 ans', '15-19 ans', '20-24 ans', '25-49 ans', '50 ans et +', 'TOTAL'],
    lignes: ['Décès maternels', 'Décès néonatal Précoce (0 à 7 jours)', 'Décès néonatal tardif (8 à 28 jours)'],
  },
  // ── IV. Tests rapides ──
  T40: {
    numero: 40,
    titre: 'Diagnostics biologique du paludisme',
    texte: 'Noter au niveau du prestataire de soins le nombre de TDR réalisé pour le diagnostic du paludisme par tranche d’âge selon les modalités positif, négatif ou invalide.',
    legende: '*femmes enceintes est comprise dans les différentes tranches d’âge.\n** il s’agit de résultats de gouttes épaisse (positive/négatives) réalisées dans une autre structure de santé (laboratoire privé ou centre de santé).',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'Total', 'Femmes enceintes*'],
    lignes: [
      'TDR positifs',
      'TDR négatifs',
      'TDR invalides',
      'GE positives réalisées hors de la structure de santé**',
      'GE négatives réalisées hors de la structure de santé**',
    ],
  },
  T41: {
    numero: 41,
    titre: 'Réalisation des tests du VIH',
    texte: 'Noter pour le poste de dépistage (CDIP et PTME) le nombre de test réalisés, le nombre de test réactifs, le nombre de test non réactifs, le nombre de tests invalides, le nombre de personnes dépistées positives au VIH, le nombre de personnes dépistées négatives au VIH, le nombre de résultats indéterminés.',
    legende: 'Tests* = nombre de cassettes/bandelettes utilisées.\nExemple : 1 bandelette de determine utilisée = 1 test, 1 bandelette de Stat-Pak utilisée = 1 test.',
    colonnes: ['TOTAL', 'Homme', 'Femme'],
    lignes: [
      'Total de tests* réalisés',
      'Total de test Positif (test réactif)',
      'Total de tests négatifs (Non Réactif)',
      'Total de tests invalides*',
      'Total de personnes dépistées positives au VIH',
      'Total de personnes dépistées négatives au VIH',
      'Total de résultats indéterminés**',
    ],
  },
  // ── V. Laboratoire ──
  T42: {
    numero: 42,
    titre: 'Type d’examens et cotation des examens de laboratoire par spécialité',
    texte: 'Noter par spécialité le nombre d’examens réalisés et le nombre total de B correspondant.',
    colonnes: ['Nombre d’examens', 'Nombre de B'],
    lignes: [
      'Hématologie',
      'Biochimie',
      'Bactériologie-virologie',
      'Parasitologie',
      'Immunologie',
      'Histologie',
      'Autre spécialités',
      'Total',
    ],
  },
  T43: {
    numero: 43,
    titre: 'Diagnostics biologique du paludisme',
    texte: 'Indiquer le nombre de gouttes épaisses (GE), positifs et négatifs selon les tranches d’âge et la provenance du patient.',
    legende: '*femmes enceintes est comprise dans les différentes tranches d’âge.\n* GE patient de la structure = Gouttes épaisses réalisées pour les patients ayant consulté dans l’établissement.\n** GE patient extérieur = Gouttes épaisses effectuées pour des patients venus d’une autre structure afin de réaliser l’examen de goutte épaisse dans l’établissement.',
    colonnes: [...TRANCHES_AGE.slice(0, 7), 'Total', 'Femmes enceintes*'],
    lignes: [
      'GE positives patient de la structure*',
      'GE positives patient extérieur**',
      'GE négatives patient de la structure*',
      'GE négatives patient extérieur**',
    ],
  },
  T44: {
    numero: 44,
    titre: 'Réalisation des tests du VIH',
    texte: 'Noter pour le Laboratoire, le nombre de test réalisés, le nombre de test réactif, le nombre de test non réactif, le nombre de test invalides, le nombre de personnes dépistées positives au VIH, le nombre de personnes de type VIH 1, VIH 2, VIH 1+2 et le nombre de personnes dépistées négatives au VIH.',
    legende: 'tests* = nombre de cassettes/bandelettes utilisées.',
    colonnes: ['Total', 'Homme', 'Femme'],
    lignes: [
      'Total de tests réalisés',
      'Total de test Positif (test réactif)',
      'Total de tests négatifs (Non Réactif)',
      'Total de tests invalides*',
      'Total de personnes dépistées positives au VIH',
      'Total de personnes Positives VIH-1',
      'Total de personnes Positives VIH-2',
      'Total de personnes Positives VIH-1+2',
      'Total de personnes Négatives au VIH',
    ],
  },
  // ── VI.1 Finances ──
  T45: {
    numero: 45,
    titre: 'Etat des redevances perçues au cours du mois',
    texte: 'Indiquer pour chaque type de prestation, le nombre d’acte gratuit à 100% à 30% et payant ainsi que le montant total payés par les clients et la part totales de la structure et le total des recettes.',
    colonnes: [
      'Non assurés',
      'Assurés CMU',
      'Assurances complémentaires (AC)',
      'CMU + AC',
      'Indigents',
      'Gratuit à 100%',
      'Gratuit à 30%',
      'Payant',
      'Part de la structure (Montant à recouvrer)',
      'Total Recette',
    ],
    lignes: [
      'Consultations',
      'Accouchement',
      'Urgences',
      'Mise en Observation',
      'Laboratoire',
      'Odontologie',
      'Petite chirurgie',
      'Autres',
      'Total',
    ],
  },
  T46: {
    numero: 46,
    titre: 'Etat des ressources',
    colonnes: ['Montant FCFA'],
    lignes: [
      'Ressources propres perçues (cumul)',
      'Ressources octroyées par les partenaires autres que l’Etat',
      'Fond d’action sanitaire',
    ],
  },
  T47: {
    numero: 47,
    titre: 'Etat des dépenses effectuées au cours du mois pour le centre de santé',
    texte: 'Indiquer le montant des dépenses par nature de prestations et lister le matériel en précisant le nombre (Ex : 5 Savons BF 4, 2 litres d’eau de javel).',
    colonnes: ['Montant (FCFA)', 'En Nature'],
    lignes: [
      'Fonctionnement de la chaine de froid',
      'Matériel d’entretien et de nettoyage',
      'Matériel de bureau',
      'Autres',
      'Total',
    ],
  },
}

// Tableaux préremplis automatiquement par le backend
export const TABLES_PRE_REMPLIES = [
  'T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10A', 'T10B',
  'T30A', 'T30B',
  'T38', 'T39', 'T40', 'T45',
]
